# Generated by Django 3.2.24 on 2024-05-03 00:08

import SEEGV.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ca',
            fields=[
                ('ca_no', models.BigAutoField(primary_key=True, serialize=False, verbose_name='상담톡번호')),
                ('ca_content', models.CharField(max_length=500, verbose_name='물어볼 내용')),
                ('ca_file', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='CancelReason',
            fields=[
                ('cr_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('cr_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('Card_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Charm',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('coupon_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('coupon_name', models.CharField(max_length=100)),
                ('coupon_date', models.DateField()),
                ('coupon_discount', models.IntegerField()),
                ('coupon_txt', models.CharField(max_length=100)),
                ('coupon_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CouponCategory',
            fields=[
                ('cc_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('coupon_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CsOption',
            fields=[
                ('cso_no', models.BigAutoField(primary_key=True, serialize=False, verbose_name='번호seq')),
                ('cso_name', models.CharField(max_length=20, verbose_name='분류1')),
            ],
        ),
        migrations.CreateModel(
            name='CsOption2',
            fields=[
                ('cso2_no', models.BigAutoField(primary_key=True, serialize=False, verbose_name='번호seq2')),
                ('cso2_name', models.CharField(max_length=20, verbose_name='분류2')),
                ('cso_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.csoption')),
            ],
        ),
        migrations.CreateModel(
            name='CsOption3',
            fields=[
                ('cso3_no', models.BigAutoField(primary_key=True, serialize=False, verbose_name='번호seq3')),
                ('cso3_name', models.CharField(max_length=20, verbose_name='분류3')),
                ('cso2_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.csoption2')),
            ],
        ),
        migrations.CreateModel(
            name='Dayofweek',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_no', models.BigAutoField(primary_key=True, serialize=False, verbose_name='이벤트 번호')),
                ('event_name', models.CharField(max_length=30, verbose_name='이벤트 이름')),
                ('event_winnum', models.IntegerField(null=True, verbose_name='이벤트 당첨인원')),
                ('event_start', models.DateField(verbose_name='이벤트 시작일')),
                ('event_end', models.DateField(verbose_name='이벤트 종료일')),
                ('event_Announce', models.DateField(null=True, verbose_name='이벤트 당첨자 발표일')),
                ('eb_type', models.CharField(max_length=30, null=True, verbose_name='이벤트 타입')),
                ('ebc_name', models.CharField(max_length=30, null=True, verbose_name='이벤트 게시물 제목')),
                ('ebc_content', models.FileField(blank=True, null=True, upload_to='eventCimg')),
                ('event_faceimg', models.FileField(blank=True, null=True, upload_to='faceimg')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Kind',
            fields=[
                ('eK_no', models.BigAutoField(primary_key=True, serialize=False, verbose_name='이벤트 유형 seq')),
                ('eK_name', models.CharField(max_length=30, verbose_name='이벤트 유형 이름')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Kind2',
            fields=[
                ('ek_no2', models.BigAutoField(primary_key=True, serialize=False, verbose_name='이벤트 유형 seq2')),
                ('ek_name2', models.CharField(max_length=30, verbose_name='이벤트 유형 이름')),
                ('ek_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.event_kind', verbose_name='이벤트 유형 seq')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Method',
            fields=[
                ('eM_no', models.BigAutoField(primary_key=True, serialize=False, verbose_name='이벤트 응모 방법 번호')),
                ('eM_name', models.CharField(max_length=20, verbose_name='이벤트 응모방법 이름')),
            ],
        ),
        migrations.CreateModel(
            name='FQ',
            fields=[
                ('fq_no', models.BigAutoField(primary_key=True, serialize=False, verbose_name='fq번호')),
                ('fq_content', models.CharField(max_length=2000, verbose_name='컨탠츠 내용')),
                ('fq_title', models.CharField(max_length=200, verbose_name='컨탠츠 제목')),
                ('fq_regdate', models.DateField(null=True, verbose_name='컨텐츠 등록일')),
                ('fq_hit', models.IntegerField(default=0, verbose_name='컨탠츠 조회수')),
                ('fqo_name', models.CharField(max_length=30, verbose_name='분류 이름')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Giftcard',
            fields=[
                ('giftcard_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('giftcard_number', models.IntegerField(null=True)),
                ('giftcard_balance', models.IntegerField()),
                ('giftcard_pw', models.CharField(max_length=100)),
                ('giftcard_price', models.IntegerField()),
                ('giftcard_period', models.DateField()),
                ('cc_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.couponcategory')),
            ],
        ),
        migrations.CreateModel(
            name='GiftcardPrice',
            fields=[
                ('giftcardPrice_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('giftcardPrice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GiftconState',
            fields=[
                ('gs_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('giftcon_state', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GiftconUser',
            fields=[
                ('giftconUser_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=100)),
                ('userName', models.CharField(max_length=100)),
                ('userTel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GoldenEgg',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('image', models.FileField(blank=True, null=True, upload_to=SEEGV.models.id_dir_path)),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('floor', models.CharField(max_length=10, null=True)),
                ('totseat', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HallSchedule',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('ondate', models.DateField()),
                ('stime', models.CharField(max_length=20)),
                ('etime', models.CharField(max_length=20)),
                ('Hall_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.hall')),
            ],
        ),
        migrations.CreateModel(
            name='HallSeat',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('srow', models.CharField(max_length=2)),
                ('scol', models.CharField(max_length=2)),
                ('Hall_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.hall')),
            ],
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('mainC_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('mainC_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MemberInfo',
            fields=[
                ('memberInfo_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('memberInfo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('member_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('member_name', models.CharField(max_length=100)),
                ('member_id', models.CharField(max_length=100)),
                ('member_pw', models.CharField(max_length=100)),
                ('member_years', models.CharField(max_length=100)),
                ('member_month', models.CharField(max_length=100)),
                ('member_day', models.CharField(max_length=100)),
                ('member_tel1', models.CharField(max_length=100)),
                ('member_tel2', models.CharField(max_length=100)),
                ('member_tel3', models.CharField(max_length=100)),
                ('member_mailId', models.CharField(max_length=100)),
                ('member_mailAddress', models.CharField(max_length=100)),
                ('member_gender', models.IntegerField()),
                ('member_vipPoint', models.IntegerField(default=0)),
                ('memberInfo_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.memberinfo')),
            ],
        ),
        migrations.CreateModel(
            name='MemberType',
            fields=[
                ('memberType_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('member_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('krname', models.CharField(max_length=100)),
                ('ername', models.CharField(max_length=100)),
                ('story', models.CharField(max_length=1000, null=True)),
                ('runtime', models.CharField(max_length=5)),
                ('image', models.FileField(blank=True, null=True, upload_to=SEEGV.models.id_dir_path)),
                ('opendate', models.DateField()),
                ('site', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieCoupon',
            fields=[
                ('mc_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('mc_name', models.CharField(max_length=100)),
                ('mc_week', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MovieReview',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('uploadtext', models.CharField(max_length=1000)),
                ('recommand', models.IntegerField()),
                ('uploaddate', models.DateField()),
                ('Charm_1', models.IntegerField(null=True)),
                ('Charm_2', models.IntegerField(null=True)),
                ('Charm_3', models.IntegerField(null=True)),
                ('Charm_4', models.IntegerField(null=True)),
                ('Charm_5', models.IntegerField(null=True)),
                ('Emotion_1', models.IntegerField(null=True)),
                ('Emotion_2', models.IntegerField(null=True)),
                ('Emotion_3', models.IntegerField(null=True)),
                ('Emotion_4', models.IntegerField(null=True)),
                ('Emotion_5', models.IntegerField(null=True)),
                ('GoldenEgg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.goldenegg')),
            ],
        ),
        migrations.CreateModel(
            name='MovieType',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('nw_no', models.BigAutoField(primary_key=True, serialize=False, verbose_name='번호')),
                ('nw_title', models.CharField(max_length=300, verbose_name='컨텐츠 제목')),
                ('nw_hit', models.IntegerField(verbose_name='컨텐츠 조회수')),
                ('nw_content', models.CharField(max_length=2000, verbose_name='컨텐츠 내용')),
                ('nw_date', models.DateField(verbose_name='컨텐츠 등록일')),
                ('nwo_name', models.CharField(max_length=30, verbose_name='컨텐츠 분류 이름')),
            ],
        ),
        migrations.CreateModel(
            name='Nonmembers',
            fields=[
                ('nonmember_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('nonmember_pw', models.CharField(max_length=100)),
                ('nonmember_years', models.IntegerField()),
                ('nonmember_month', models.IntegerField()),
                ('nonmember_day', models.IntegerField()),
                ('nonmember_tel1', models.IntegerField()),
                ('nonmember_tel2', models.IntegerField()),
                ('nonmember_tel3', models.IntegerField()),
                ('nonmember_gender', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ocb_option1',
            fields=[
                ('onco_no', models.BigAutoField(primary_key=True, serialize=False, verbose_name='쿠폰 분류 seq')),
                ('onco_name', models.CharField(max_length=30, verbose_name='쿠폰분류')),
            ],
        ),
        migrations.CreateModel(
            name='Ocb_option2',
            fields=[
                ('onco2_no', models.BigAutoField(primary_key=True, serialize=False, verbose_name='쿠폰 분류 seq2')),
                ('onco2_name', models.CharField(max_length=20, verbose_name='쿠폰분류')),
                ('onco_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.ocb_option1', verbose_name='쿠폰북 1 seq')),
            ],
        ),
        migrations.CreateModel(
            name='PayStep',
            fields=[
                ('ps_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('ps_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PersonType',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PointCategory',
            fields=[
                ('pc_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('pointCategory', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PointUse',
            fields=[
                ('pointUse_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('savepoint', models.IntegerField(default=0)),
                ('usepoint', models.IntegerField(default=0)),
                ('pointUse_place', models.CharField(max_length=100)),
                ('pointUse_date', models.DateField()),
                ('member_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.members')),
                ('pc_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.pointcategory')),
            ],
        ),
        migrations.CreateModel(
            name='PreEgg',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('cate', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SeatType',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StepDetail',
            fields=[
                ('sd_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('sd_name', models.CharField(max_length=50)),
                ('ps_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.paystep')),
            ],
        ),
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                ('sc_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('sc_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('sp_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('sp_name', models.CharField(max_length=100)),
                ('sp_image', models.FileField(blank=True, null=True, upload_to='store/')),
                ('sp_items', models.CharField(max_length=100)),
                ('sp_period', models.CharField(max_length=100)),
                ('sp_periodNumber', models.IntegerField(null=True)),
                ('sp_origin', models.CharField(max_length=100, null=True)),
                ('sp_txt', models.TextField(null=True)),
                ('sp_price', models.IntegerField(null=True)),
                ('sp_discount', models.IntegerField(null=True)),
                ('sc_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.storecategory')),
            ],
        ),
        migrations.CreateModel(
            name='StoreProductState',
            fields=[
                ('sps_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('sps', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('terms_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('terms_title', models.CharField(max_length=100)),
                ('terms_item', models.CharField(max_length=100)),
                ('terms_purpose', models.TextField()),
                ('terms_period', models.CharField(max_length=100)),
                ('terms_required', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TheaterType',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('ticket_date', models.DateTimeField(auto_now_add=True)),
                ('member_no', models.IntegerField()),
                ('ticket_totalcnt', models.IntegerField()),
                ('ticket_totalprice', models.IntegerField()),
                ('ticket_gender', models.IntegerField()),
                ('ticket_age', models.IntegerField()),
                ('ticket_cancelflag', models.IntegerField()),
                ('HallSchedule_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.hallschedule')),
                ('pointUse_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SEEGV.pointuse')),
            ],
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vbo_option',
            fields=[
                ('vboo_no', models.BigAutoField(primary_key=True, serialize=False, verbose_name='번호seq')),
                ('vboo_name', models.CharField(max_length=20, verbose_name='분류1')),
            ],
        ),
        migrations.CreateModel(
            name='ViewableAge',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VipClient',
            fields=[
                ('vigc_no', models.BigAutoField(primary_key=True, serialize=False, verbose_name='번호')),
                ('vipg_title', models.CharField(max_length=150, verbose_name='제목')),
                ('vipg_content', models.CharField(max_length=500, verbose_name='내용')),
            ],
        ),
        migrations.CreateModel(
            name='VipGrade_option',
            fields=[
                ('vipgo_no', models.BigAutoField(primary_key=True, serialize=False, verbose_name='등급번호seq')),
                ('vipgo_name', models.CharField(max_length=20, verbose_name='고객 등급 이름')),
                ('vipgo_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vipstamp_option1',
            fields=[
                ('vso_no', models.BigAutoField(primary_key=True, serialize=False, verbose_name='번호seq')),
                ('vs_name', models.CharField(max_length=20, verbose_name='분류1')),
            ],
        ),
        migrations.CreateModel(
            name='Vmobiec_option',
            fields=[
                ('vmco_no', models.BigAutoField(primary_key=True, serialize=False, verbose_name='번호seq')),
                ('vmco_score', models.IntegerField(verbose_name='쿠폰당 갯수')),
                ('vmco_op', models.CharField(max_length=20, null=True, verbose_name='분류 이름')),
                ('onco2_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.ocb_option2', verbose_name='쿠폰seq')),
                ('vipgo_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.vipgrade_option', verbose_name='등급')),
            ],
        ),
        migrations.CreateModel(
            name='Vipstamp_option2',
            fields=[
                ('vso2_no', models.BigAutoField(primary_key=True, serialize=False, verbose_name='번호 seq')),
                ('vos2_name', models.CharField(max_length=20, verbose_name='분류2 이름')),
                ('vso_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.vipstamp_option1', verbose_name='분류1 번호')),
            ],
        ),
        migrations.CreateModel(
            name='Vipstamp',
            fields=[
                ('vips_no', models.BigAutoField(primary_key=True, serialize=False, verbose_name='번호')),
                ('vips_number', models.IntegerField(verbose_name='적립 숫자')),
                ('vipgo_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.vipgrade_option', verbose_name='등급 받기')),
                ('vso2_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.vipstamp_option2', verbose_name='번호 seq')),
            ],
        ),
        migrations.CreateModel(
            name='VipPointSave',
            fields=[
                ('vipps_no', models.BigAutoField(primary_key=True, serialize=False, verbose_name='vip 포인트 적립')),
                ('vipps_point', models.IntegerField(verbose_name='적립 포인트')),
                ('vipps_date', models.DateField(verbose_name='포인트 적립일')),
                ('member_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.members', verbose_name='사용자 회원정보 seq')),
                ('pc_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.pointcategory', verbose_name='포인트 종류 seq')),
            ],
        ),
        migrations.CreateModel(
            name='VipGrade_manage',
            fields=[
                ('vigm_no', models.BigAutoField(primary_key=True, serialize=False, verbose_name='번호 seq')),
                ('vigm_sd', models.DateField(null=True, verbose_name='승급된 년/월')),
                ('vigm_ed', models.DateField(null=True, verbose_name='종료된 년/월')),
                ('member_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.members', verbose_name='회원 정보')),
                ('vipgo_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.vipgrade_option', verbose_name='회원 등급 받기')),
            ],
        ),
        migrations.CreateModel(
            name='VIPcouponmemberManager',
            fields=[
                ('vipcm_no', models.BigAutoField(primary_key=True, serialize=False, verbose_name='번호')),
                ('vipcm_number', models.IntegerField(verbose_name='수량')),
                ('vipcm_start', models.DateField(verbose_name='이벤트 시작일')),
                ('vipcm_end', models.DateField(verbose_name='이벤트 종료일')),
                ('member_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.members', verbose_name='회원 번호 받아오기')),
                ('onco2_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.ocb_option2', verbose_name='쿠폰 seq')),
            ],
        ),
        migrations.CreateModel(
            name='VIPbenifitotherManager',
            fields=[
                ('vipbo_no', models.BigAutoField(primary_key=True, serialize=False, verbose_name='번호')),
                ('vipbo_number', models.CharField(max_length=40, null=True, verbose_name='수량')),
                ('vipbo_start', models.DateField(verbose_name='이벤트 시작일')),
                ('vipbo_end', models.DateField(verbose_name='이벤트 종료일')),
                ('member_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.members', verbose_name='회원 번호 받아오기')),
                ('vboo_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.vbo_option', verbose_name='쿠폰 seq')),
            ],
        ),
        migrations.CreateModel(
            name='VIPbenifitmemberManager',
            fields=[
                ('vipbM_no', models.BigAutoField(primary_key=True, serialize=False, verbose_name='번호')),
                ('vbmm_number', models.IntegerField(verbose_name='수량')),
                ('member_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.members', verbose_name='회원 번호 받아오기')),
                ('vso2_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.vipstamp_option2', verbose_name='쿠폰 seq')),
            ],
        ),
        migrations.CreateModel(
            name='Vbo',
            fields=[
                ('vbo_no', models.BigAutoField(primary_key=True, serialize=False, verbose_name='번호 seq')),
                ('vbo_price', models.CharField(max_length=30, null=True, verbose_name='상품')),
                ('vboo_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.vbo_option', verbose_name='번호seq')),
                ('vipgo_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.vipgrade_option', verbose_name='등급')),
            ],
        ),
        migrations.CreateModel(
            name='TicketSeat',
            fields=[
                ('ts_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('HallSeat_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.hallseat')),
                ('ticket_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketCoupon',
            fields=[
                ('tc_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('coupon_useno', models.IntegerField()),
                ('tc_date', models.DateTimeField(auto_now_add=True)),
                ('tc_price', models.IntegerField()),
                ('sd_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.stepdetail')),
                ('ticket_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketCancel',
            fields=[
                ('tcc_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('cr_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.cancelreason')),
                ('ticket_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.ticket')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='vipps_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SEEGV.vippointsave'),
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20)),
                ('traffic', models.CharField(max_length=1000)),
                ('parking', models.CharField(max_length=1000)),
                ('tothalls', models.CharField(max_length=10, null=True)),
                ('totseats', models.CharField(max_length=10, null=True)),
                ('info', models.CharField(max_length=200, null=True)),
                ('Region_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.region')),
                ('TheaterType_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.theatertype')),
            ],
        ),
        migrations.CreateModel(
            name='Termsdata5',
            fields=[
                ('termsdata5_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('td_zipcode', models.IntegerField(null=True)),
                ('td_address', models.CharField(max_length=100, null=True)),
                ('td_addressDetail', models.CharField(max_length=100, null=True)),
                ('member_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.members')),
                ('terms_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.terms')),
            ],
        ),
        migrations.CreateModel(
            name='Termsdata4',
            fields=[
                ('termsdata4_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('td_anniversary', models.DateField(null=True)),
                ('td_anniversaryName', models.CharField(max_length=100, null=True)),
                ('member_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.members')),
                ('terms_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.terms')),
            ],
        ),
        migrations.CreateModel(
            name='Termsdata3',
            fields=[
                ('termsdata3_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('td_time', models.CharField(max_length=100, null=True)),
                ('member_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.members')),
                ('terms_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.terms')),
            ],
        ),
        migrations.CreateModel(
            name='Termsdata2',
            fields=[
                ('termsdata2_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('td_weekday', models.CharField(max_length=100, null=True)),
                ('member_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.members')),
                ('terms_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.terms')),
            ],
        ),
        migrations.CreateModel(
            name='Termsdata1',
            fields=[
                ('termsdata1_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('td_genre1', models.CharField(max_length=100, null=True)),
                ('td_genre2', models.CharField(max_length=100, null=True)),
                ('member_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.members')),
                ('terms_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.terms')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('subC_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('subC_category', models.CharField(max_length=100)),
                ('mainC_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.maincategory')),
            ],
        ),
        migrations.CreateModel(
            name='StoreProductUse',
            fields=[
                ('spu_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('sp_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.storeproduct')),
                ('th_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.theater')),
            ],
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='sps_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.storeproductstate'),
        ),
        migrations.CreateModel(
            name='StoreOrder',
            fields=[
                ('order_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=100)),
                ('order_date', models.DateField()),
                ('order_price', models.IntegerField()),
                ('order_discount', models.IntegerField(null=True)),
                ('order_payment', models.IntegerField()),
                ('order_method', models.CharField(max_length=100)),
                ('order_state', models.IntegerField()),
                ('giftconUser_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SEEGV.giftconuser')),
                ('member_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.members')),
                ('pointUse_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SEEGV.pointuse')),
                ('vipps_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SEEGV.vippointsave')),
            ],
        ),
        migrations.CreateModel(
            name='Stillcut',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(blank=True, null=True, upload_to=SEEGV.models.id_dir_path)),
                ('Movie_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.movie')),
            ],
        ),
        migrations.CreateModel(
            name='ReportCount',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('MovieReview_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.moviereview')),
                ('Report_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.report')),
                ('member_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.members')),
            ],
        ),
        migrations.CreateModel(
            name='RecommandCount',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('MovieReview_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.moviereview')),
                ('member_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.members')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=100, null=True)),
                ('filename', models.CharField(max_length=100, null=True)),
                ('profileimage', models.FileField(blank=True, null=True, upload_to=SEEGV.models.nickname_dir_path)),
                ('member_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.members')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('Productorder_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=100)),
                ('order_count', models.IntegerField()),
                ('order_price', models.IntegerField()),
                ('order_discount', models.IntegerField()),
                ('order_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SEEGV.storeorder')),
                ('sp_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.storeproduct')),
            ],
        ),
        migrations.CreateModel(
            name='PointRule',
            fields=[
                ('PointRule_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('pointRule_type', models.IntegerField()),
                ('pointRule', models.IntegerField()),
                ('pointRule_dsc', models.CharField(max_length=100, null=True)),
                ('pc_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.pointcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('point_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('point', models.IntegerField()),
                ('member_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.members')),
                ('pc_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.pointcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('krname', models.CharField(max_length=20)),
                ('enname', models.CharField(max_length=20, null=True)),
                ('intro', models.CharField(max_length=1000, null=True)),
                ('image', models.FileField(max_length=1000, null=True, upload_to='')),
                ('birth', models.CharField(max_length=20, null=True)),
                ('award', models.CharField(max_length=100, null=True)),
                ('site', models.CharField(max_length=100, null=True)),
                ('body', models.CharField(max_length=100, null=True)),
                ('academic', models.CharField(max_length=100, null=True)),
                ('family', models.CharField(max_length=100, null=True)),
                ('hobby', models.CharField(max_length=100, null=True)),
                ('Country_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.country')),
            ],
        ),
        migrations.CreateModel(
            name='PayCard',
            fields=[
                ('pc_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('card_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.card')),
                ('ticket_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='PackageProduct',
            fields=[
                ('pp_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('pp_name', models.CharField(max_length=100)),
                ('pp_price', models.IntegerField()),
                ('pp_count', models.IntegerField()),
                ('pp_periodNumber', models.IntegerField()),
                ('pp_origin', models.CharField(max_length=100, null=True)),
                ('sp_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.storeproduct')),
            ],
        ),
        migrations.AddField(
            model_name='moviereview',
            name='profile_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.profile'),
        ),
        migrations.AddField(
            model_name='moviereview',
            name='ticket_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.ticket'),
        ),
        migrations.CreateModel(
            name='MoviePreview',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('Movie_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.movie')),
                ('PreEgg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.preegg')),
                ('member_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.members')),
            ],
        ),
        migrations.CreateModel(
            name='MoviePersonMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10)),
                ('Movie_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.movie')),
                ('Person_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.person')),
            ],
        ),
        migrations.CreateModel(
            name='MovieGenreMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Genre_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.genre')),
                ('Movie_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieCouponTheaterType',
            fields=[
                ('mctt_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('mc_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.moviecoupon')),
                ('screen_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.screen')),
            ],
        ),
        migrations.CreateModel(
            name='MovieCouponTheaters',
            fields=[
                ('mct_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('mc_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.moviecoupon')),
                ('th_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.theater')),
            ],
        ),
        migrations.CreateModel(
            name='MovieCouponInfo',
            fields=[
                ('mci_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('mci_number', models.IntegerField()),
                ('mci_date', models.DateField()),
                ('mcu_date', models.DateField(null=True)),
                ('mc_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.moviecoupon')),
                ('member_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SEEGV.members')),
            ],
        ),
        migrations.CreateModel(
            name='MovieCountryMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.country')),
                ('Movie_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='MovieType_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.movietype'),
        ),
        migrations.AddField(
            model_name='movie',
            name='ViewableAge_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.viewableage'),
        ),
        migrations.AddField(
            model_name='members',
            name='memberType_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.membertype'),
        ),
        migrations.AddField(
            model_name='members',
            name='member_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.vipgrade_option'),
        ),
        migrations.CreateModel(
            name='MemberJoinDate',
            fields=[
                ('mjd_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('mjd_date', models.DateField()),
                ('mjd_dormantdate', models.DateField(blank=True, null=True)),
                ('mjd_leave', models.DateField(blank=True, null=True)),
                ('member_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.members')),
            ],
        ),
        migrations.AddField(
            model_name='hallseat',
            name='SeatType_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.seattype'),
        ),
        migrations.AddField(
            model_name='hallschedule',
            name='Movie_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.movie'),
        ),
        migrations.CreateModel(
            name='HallPrice',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.CharField(max_length=10)),
                ('Dayofweek_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.dayofweek')),
                ('Screen_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.screen')),
            ],
        ),
        migrations.AddField(
            model_name='hall',
            name='Screen_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.screen'),
        ),
        migrations.AddField(
            model_name='hall',
            name='Theater_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.theater'),
        ),
        migrations.CreateModel(
            name='GroupAsk',
            fields=[
                ('ga_no', models.BigAutoField(primary_key=True, serialize=False, verbose_name='번호')),
                ('ga_date', models.DateField(verbose_name='관람 희망일')),
                ('ga_time', models.IntegerField(verbose_name='관람 시간')),
                ('ga_person', models.IntegerField(verbose_name='관람 희망 인원')),
                ('ga_content', models.CharField(max_length=100, verbose_name='내용 데이터')),
                ('ga_membername', models.CharField(max_length=15, verbose_name='문의자명')),
                ('ga_tel', models.IntegerField(verbose_name='연락처')),
                ('ga_email', models.CharField(max_length=30, verbose_name='이메일')),
                ('theater_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.theater')),
            ],
        ),
        migrations.CreateModel(
            name='GiftconCategory',
            fields=[
                ('gc_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('gc_category', models.CharField(max_length=100)),
                ('gc_categoryNo', models.CharField(max_length=100)),
                ('pp_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SEEGV.packageproduct')),
                ('sc_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SEEGV.storecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Giftcon',
            fields=[
                ('giftcon_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('giftcon_number', models.IntegerField(null=True)),
                ('order_day', models.DateField()),
                ('giftcon_period', models.DateField()),
                ('gc_categoryNo', models.CharField(max_length=100, null=True)),
                ('gs_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.giftconstate')),
                ('order_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SEEGV.storeorder')),
                ('pp_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SEEGV.packageproduct')),
                ('sp_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.storeproduct')),
                ('user_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SEEGV.members')),
            ],
        ),
        migrations.CreateModel(
            name='GiftcardUse',
            fields=[
                ('giftcarduse_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('giftcarduse_date', models.DateField(null=True)),
                ('giftcarduse_price', models.IntegerField(null=True)),
                ('giftcard_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.giftcard')),
            ],
        ),
        migrations.AddField(
            model_name='giftcard',
            name='gs_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SEEGV.giftconstate'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='member_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SEEGV.members'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='order_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.storeorder'),
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('eventcate_no', models.BigAutoField(primary_key=True, serialize=False, verbose_name='유형 관리 번호')),
                ('ek_no2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.event_kind2', verbose_name='이벤트 유형 seq')),
                ('event_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.event', verbose_name='이벤트 번호')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='eM_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.event_method'),
        ),
        migrations.AddField(
            model_name='event',
            name='vipgo_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SEEGV.vipgrade_option', verbose_name='가능한 회원 최소 등급 받기'),
        ),
        migrations.CreateModel(
            name='Ea',
            fields=[
                ('ea_no', models.BigAutoField(primary_key=True, serialize=False, verbose_name='번호')),
                ('ea_op', models.CharField(max_length=30, verbose_name='유형 분류')),
                ('ea_title', models.CharField(max_length=30, verbose_name='제목')),
                ('ea_content', models.CharField(max_length=2000, verbose_name='내용')),
                ('ea_file', models.FileField(blank=True, null=True, upload_to='support/')),
                ('ea_regdate', models.DateField()),
                ('ea_state', models.CharField(max_length=30, null=True)),
                ('ea_satisfy', models.CharField(max_length=30, null=True)),
                ('ea_mcontent', models.CharField(max_length=2000, null=True)),
                ('member_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.members', verbose_name='회원 정보 seq')),
                ('theater_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SEEGV.theater', verbose_name='지역 분류 seq')),
            ],
        ),
        migrations.CreateModel(
            name='CsOption4',
            fields=[
                ('cso4_no', models.BigAutoField(primary_key=True, serialize=False, verbose_name='번호seq3')),
                ('cso4_name', models.CharField(max_length=30, verbose_name='분류3')),
                ('cso3_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.csoption3')),
            ],
        ),
        migrations.CreateModel(
            name='Cs',
            fields=[
                ('cs_no', models.BigAutoField(primary_key=True, serialize=False, verbose_name='번호')),
                ('cs_url', models.CharField(max_length=100, null=True, verbose_name='url 저장 컨탠츠')),
                ('cs_content', models.CharField(max_length=300, null=True, verbose_name='컨탠츠 내용')),
                ('cso2_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.csoption2')),
                ('cso3_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.csoption3')),
                ('cso_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.csoption')),
            ],
        ),
        migrations.CreateModel(
            name='CouponTheatersType',
            fields=[
                ('ctt_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('coupon_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.coupon')),
                ('screen_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.screen')),
            ],
        ),
        migrations.CreateModel(
            name='CouponTheaters',
            fields=[
                ('ct_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('coupon_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.coupon')),
                ('th_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.theater')),
            ],
        ),
        migrations.CreateModel(
            name='CouponInfo',
            fields=[
                ('ci_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('ci_number', models.IntegerField()),
                ('mci_date', models.DateField()),
                ('cu_date', models.DateField(null=True)),
                ('coupon_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.coupon')),
                ('member_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SEEGV.members')),
            ],
        ),
        migrations.AddField(
            model_name='coupon',
            name='cc_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.couponcategory'),
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('bookmark_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('member_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.members')),
                ('th_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.theater')),
            ],
        ),
        migrations.CreateModel(
            name='ApplyUrl',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False, verbose_name='시퀀스')),
                ('urlname', models.CharField(max_length=200, verbose_name='url')),
                ('event_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.event', verbose_name='이벤트 번호 받기')),
            ],
        ),
        migrations.CreateModel(
            name='ApplyMember',
            fields=[
                ('aM_NO', models.BigAutoField(primary_key=True, serialize=False, verbose_name='이벤트 응모자 번호')),
                ('aM_date', models.DateField(verbose_name='응모 일시')),
                ('aM_win', models.BooleanField(null=True, verbose_name='당첨 여부')),
                ('event_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.event', verbose_name='이벤트 번호 받기')),
                ('member_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.members', verbose_name='등급자 번호 받기')),
            ],
        ),
        migrations.CreateModel(
            name='Apply_Theater',
            fields=[
                ('aT_no', models.BigAutoField(primary_key=True, serialize=False, verbose_name='이벤트 적용하는 극장여부 시퀀스')),
                ('Theater_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SEEGV.theater', verbose_name='이벤트 진행 극장')),
                ('event_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SEEGV.event', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('agreement_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('useragreement', models.IntegerField()),
                ('member_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.members')),
                ('terms_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.terms')),
            ],
        ),
        migrations.CreateModel(
            name='AddList',
            fields=[
                ('addList_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('addList_count', models.IntegerField()),
                ('addList_date', models.DateField()),
                ('addList_checkde', models.BooleanField(default=0)),
                ('member_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.members')),
                ('sp_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEGV.storeproduct')),
            ],
        ),
    ]
